# Generated by Django 5.0.4 on 2024-05-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0003_candidate_no_votes_candidate_yes_votes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='no_votes',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='yes_votes',
        ),
    ]
