# Generated by Django 5.0.4 on 2024-05-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0005_authorizeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorizedUser',
        ),
    ]
